// <auto-generated />
using System;
using HolisticDepartmentExamSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HolisticDepartmentExamSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201233130_AddPerformanceIndexesAndSecurity")]
    partial class AddPerformanceIndexesAndSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        
                        .HasColumnName("action");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("choice_id");

                    b.Property<string>("ChoiceText")
                        
                        .HasColumnName("choice_text");

                    b.Property<bool>("IsCorrect")
                        
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        
                        .HasColumnName("question_id");

                    b.HasKey("ChoiceId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("exam_id");

                    b.Property<DateTime>("CreatedAt")
                        
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("ResultsPublished")
                        
                        .HasColumnName("results_published");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        
                        .HasColumnName("title");

                    b.Property<int>("TotalMarks")
                        
                        .HasColumnName("total_marks");

                    b.HasKey("ExamId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ResultsPublished");

                    b.HasIndex("Status");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("answer_id");

                    b.Property<int>("AttemptId")
                        
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsFlagged")
                        
                        .HasColumnName("is_flagged");

                    b.Property<int>("QuestionId")
                        
                        .HasColumnName("question_id");

                    b.Property<int?>("SelectedChoiceId")
                        
                        .HasColumnName("selected_choice_id");

                    b.HasKey("AnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedChoiceId");

                    b.ToTable("ExamAnswers");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("attempt_id");

                    b.Property<DateTime?>("EndTime")
                        
                        .HasColumnName("end_time");

                    b.Property<int>("ExamId")
                        
                        .HasColumnName("exam_id");

                    b.Property<bool>("IsBlocked")
                        
                        .HasColumnName("is_blocked");

                    b.Property<DateTime>("StartTime")
                        
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        
                        .HasColumnName("student_id");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("IsBlocked");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamPassword", b =>
                {
                    b.Property<int>("PasswordId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("password_id");

                    b.Property<int>("ExamId")
                        
                        .HasColumnName("exam_id");

                    b.Property<DateTime>("ExpiresAt")
                        
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        
                        .HasColumnName("is_used");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        
                        .HasColumnName("password_hash");

                    b.Property<int>("StudentId")
                        
                        .HasColumnName("student_id");

                    b.HasKey("PasswordId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExamId", "StudentId");

                    b.ToTable("ExamPasswords");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("feedback_id");

                    b.Property<string>("Comment")
                        
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        
                        .HasColumnName("created_at");

                    b.Property<int>("ExamId")
                        
                        .HasColumnName("exam_id");

                    b.Property<int>("Rating")
                        
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("question_id");

                    b.Property<int>("ExamId")
                        
                        .HasColumnName("exam_id");

                    b.Property<int>("Marks")
                        
                        .HasColumnName("marks");

                    b.Property<int>("QuestionOrder")
                        
                        .HasColumnName("question_order");

                    b.Property<string>("QuestionText")
                        
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        
                        .HasColumnName("question_type");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("result_id");

                    b.Property<int>("AttemptId")
                        
                        .HasColumnName("attempt_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        
                        .HasColumnName("grade");

                    b.Property<string>("PassStatus")
                        .HasMaxLength(20)
                        
                        .HasColumnName("pass_status");

                    b.Property<DateTime>("PublishedAt")
                        
                        .HasColumnName("published_at");

                    b.Property<int>("TotalScore")
                        
                        .HasColumnName("total_score");

                    b.HasKey("ResultId");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Coordinator"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("student_id");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        
                        .HasColumnName("full_name");

                    b.Property<int>("UserId")
                        
                        .HasColumnName("user_id");

                    b.Property<int>("YearOfStudy")
                        
                        .HasColumnName("year_of_study");

                    b.HasKey("StudentId");

                    b.HasIndex("Email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastActivity")
                        
                        .HasColumnName("last_activity");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        
                        .HasColumnName("role_id");

                    b.Property<bool>("Status")
                        
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("LastActivity");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$7J5/wvVHvKlZ8Z8Z8Z8Z8eZ8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8",
                            RoleId = 1,
                            Status = true,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ActivityLog", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Choice", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Exam", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.User", "Creator")
                        .WithMany("ExamsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamAnswer", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.ExamAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolisticDepartmentExamSystem.Models.Question", "Question")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolisticDepartmentExamSystem.Models.Choice", "SelectedChoice")
                        .WithMany()
                        .HasForeignKey("SelectedChoiceId");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamAttempt", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Exam", "Exam")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolisticDepartmentExamSystem.Models.Student", "Student")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamPassword", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Exam", "Exam")
                        .WithMany("ExamPasswords")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolisticDepartmentExamSystem.Models.Student", "Student")
                        .WithMany("ExamPasswords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Feedback", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Exam", "Exam")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolisticDepartmentExamSystem.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Question", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Result", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.ExamAttempt", "Attempt")
                        .WithOne("Result")
                        .HasForeignKey("HolisticDepartmentExamSystem.Models.Result", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Student", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("HolisticDepartmentExamSystem.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.User", b =>
                {
                    b.HasOne("HolisticDepartmentExamSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Exam", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("ExamPasswords");

                    b.Navigation("Feedbacks");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.ExamAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.Student", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("ExamPasswords");
                });

            modelBuilder.Entity("HolisticDepartmentExamSystem.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ExamsCreated");

                    b.Navigation("Feedbacks");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
